version: "3.8"

services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=MyP@ssw0rd!!
    ports:
      - "5341:5341"
      - "8080:80"
    volumes:
      - seq-data:/data

volumes:
  seq-data: