version: '3.8'

services:
  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:alpine-7.0-latest
    container_name: zabbix-java-gateway
    restart: unless-stopped

  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:alpine-7.0-latest
    container_name: zabbix-server-mysql
    environment:
      DB_SERVER_HOST: "0.0.0.0"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "101299"
      MYSQL_ROOT_PASSWORD: "101299"
      ZBX_JAVAGATEWAY: "zabbix-java-gateway"
    ports:
      - "10051:10051"
    restart: unless-stopped

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.0-latest
    container_name: zabbix-web-nginx-mysql
    environment:
      ZBX_SERVER_HOST: "zabbix-server-mysql"
      DB_SERVER_HOST: "0.0.0.0"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "101299"
      MYSQL_ROOT_PASSWORD: "101299"
    ports:
      - "9000:8080"
    restart: unless-stopped