version: '3'
services:
  nginx:
    build: .
    container_name: nginx-tlsur
    ports:
      - "80:80"
      - "443:443"
      - "1935:1935"  # Puerto para RTMP
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/html:/etc/nginx/html
    command: ["nginx", "-g", "daemon off;"]
