version: '3.9'

services:
  back-nameapp:
    build: .
    container_name: back-nameapp
    command: sh -c "uvicorn app:app --reload --port=0000 --host=0.0.0.0"
    ports:
      - 0001:0000
    volumes:
      - .:/app
