version: '3.5'

services:
  cacti-poller:
    image: "smcline06/cacti"
    container_name: cacti_poller
    domainname: examplepoller.com
    hostname: cactipoller
    ports:
      - "8089:80"
      - "8443:443"
    environment:
      - DB_NAME=cacti_poller
       - DB_USER=${CACTI_POLLER_DB_USER}
       - DB_PASS=${CACTI_POLLER_DB_PASS}
       - DB_HOST=${CACTI_REMOTE_DB_HOST}
      - DB_PORT=3306
      - RDB_NAME=cacti_master
       - RDB_USER=${CACTI_DB_USER}
       - RDB_PASS=${CACTI_DB_PASS}
       - RDB_HOST=${CACTI_REMOTE_DB_HOST}
      - RDB_PORT=3306
       - DB_ROOT_PASS=${CACTI_POLLER_DB_ROOT_PASS}
      - REMOTE_POLLER=1
      - INITIALIZE_DB=1
      - TZ=America/Los_Angeles
    volumes:
      - cacti-poller-data:/cacti
      - cacti-poller-spine:/spine
      - cacti-poller-backups:/backups

volumes:
  cacti-poller-data:
  cacti-poller-spine:
  cacti-poller-backups:
