version: '3.8'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql-server
    environment:
      SA_PASSWORD: '101299...'
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"